import { formatCell } from './report-registry';

/**
 * Shared PDF builder for all standardized reports (pdfmake, client-side).
 *
 * pdfmake and its embedded fonts are heavy and browser-only, so they are
 * lazy-loaded on first use (never during SSR). The SAME docDefinition powers
 * Open / Save / Print so the three actions are byte-identical.
 *
 * The numbers rendered here come straight from the server-aggregated report
 * payload — this builder never recomputes a total.
 */

let _pdfMakePromise = null;

async function getPdfMake() {
    if (!_pdfMakePromise) {
        _pdfMakePromise = (async () => {
            const pdfMakeMod = await import('pdfmake/build/pdfmake');
            const pdfFontsMod = await import('pdfmake/build/vfs_fonts');
            const pdfMake = pdfMakeMod.default || pdfMakeMod;
            // vfs shape differs across pdfmake builds — probe the known locations.
            const vfs =
                pdfFontsMod.vfs ||
                pdfFontsMod.default?.vfs ||
                pdfFontsMod.pdfMake?.vfs ||
                pdfFontsMod.default?.pdfMake?.vfs;
            if (vfs) pdfMake.vfs = vfs;
            return pdfMake;
        })();
    }
    return _pdfMakePromise;
}

const alignFor = (type) => (type === 'money' || type === 'number' ? 'right' : 'left');

/** Format a DD/MM/YYYY display date range label. */
function rangeLabel(fromDate, toDate) {
    if (!fromDate && !toDate) return '';
    const fmt = (s) => {
        const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(s || ''));
        return m ? `${m[3]}/${m[2]}/${m[1]}` : s;
    };
    if (fromDate && toDate && fromDate !== toDate) return `${fmt(fromDate)} to ${fmt(toDate)}`;
    return fmt(fromDate || toDate);
}

/**
 * Build a pdfmake document definition from a report descriptor + data.
 * @param {object} descriptor  registry descriptor
 * @param {object} data        server report payload
 * @param {object|null} company active PosCompany (header identity)
 * @param {string} fromDate
 * @param {string} toDate
 */
export function buildReportDoc(descriptor, data, company, fromDate, toDate) {
    const rows = descriptor.buildRows(data);
    const summary = descriptor.buildSummary(data);
    const cols = descriptor.columns;

    const headerCells = cols.map((c) => ({
        text: c.label,
        style: 'th',
        alignment: alignFor(c.type),
    }));

    const bodyRows = rows.map((r) =>
        cols.map((c) => ({
            text: formatCell(r[c.key], c.type),
            style: 'td',
            alignment: alignFor(c.type),
        })),
    );

    if (bodyRows.length === 0) {
        bodyRows.push([
            { text: 'No records for the selected period.', colSpan: cols.length, alignment: 'center', style: 'empty' },
            ...Array(cols.length - 1).fill({}),
        ]);
    }

    const companyBlock = company
        ? [
              { text: company.companyName || company.name || 'Company', style: 'companyName' },
              company.address ? { text: company.address, style: 'companyMeta' } : null,
              {
                  text: [
                      company.gstin ? `GSTIN: ${company.gstin}` : '',
                      company.stateName ? `State: ${company.stateCode || ''}-${company.stateName}` : '',
                  ]
                      .filter(Boolean)
                      .join('   '),
                  style: 'companyMeta',
              },
          ].filter(Boolean)
        : [{ text: 'No active company configured', style: 'companyMeta' }];

    const rangeTxt = rangeLabel(fromDate, toDate);

    // Summary band rendered as a wrapping list of "Label: value" chips.
    const summaryColumns = summary.map((s) => ({
        width: 'auto',
        margin: [0, 0, 16, 0],
        stack: [
            { text: s.label.toUpperCase(), style: 'sumLabel' },
            { text: formatCell(s.value, s.type), style: 'sumValue' },
        ],
    }));

    return {
        pageSize: 'A4',
        pageMargins: [28, 28, 28, 36],
        footer: (currentPage, pageCount) => ({
            columns: [
                { text: 'Generated by POS', style: 'footer', alignment: 'left', margin: [28, 0, 0, 0] },
                { text: `Page ${currentPage} / ${pageCount}`, style: 'footer', alignment: 'right', margin: [0, 0, 28, 0] },
            ],
        }),
        content: [
            {
                columns: [
                    { width: '*', stack: companyBlock },
                    {
                        width: 'auto',
                        stack: [
                            { text: descriptor.title, style: 'reportTitle', alignment: 'right' },
                            rangeTxt ? { text: rangeTxt, style: 'reportRange', alignment: 'right' } : null,
                        ].filter(Boolean),
                    },
                ],
            },
            { canvas: [{ type: 'line', x1: 0, y1: 6, x2: 539, y2: 6, lineWidth: 1, lineColor: '#94a3b8' }] },
            { columns: summaryColumns, columnGap: 0, margin: [0, 12, 0, 12] },
            {
                table: {
                    headerRows: 1,
                    widths: cols.map((c) => (c.type === 'text' ? '*' : 'auto')),
                    body: [headerCells, ...bodyRows],
                },
                layout: {
                    fillColor: (rowIndex) => (rowIndex === 0 ? '#f1f5f9' : rowIndex % 2 === 0 ? '#fafafa' : null),
                    hLineColor: '#e2e8f0',
                    vLineColor: '#e2e8f0',
                    hLineWidth: () => 0.5,
                    vLineWidth: () => 0.5,
                },
            },
        ],
        styles: {
            companyName: { fontSize: 15, bold: true, color: '#0f172a' },
            companyMeta: { fontSize: 8, color: '#475569', margin: [0, 1, 0, 0] },
            reportTitle: { fontSize: 16, bold: true, color: '#0f172a' },
            reportRange: { fontSize: 9, color: '#475569', margin: [0, 2, 0, 0] },
            sumLabel: { fontSize: 7, bold: true, color: '#64748b' },
            sumValue: { fontSize: 11, bold: true, color: '#0f172a', margin: [0, 1, 0, 0] },
            th: { fontSize: 8, bold: true, color: '#334155' },
            td: { fontSize: 8, color: '#1e293b' },
            empty: { fontSize: 9, italics: true, color: '#94a3b8', margin: [0, 8, 0, 8] },
            footer: { fontSize: 7, color: '#94a3b8' },
        },
        defaultStyle: { fontSize: 8 },
    };
}

function fileName(descriptor, fromDate, toDate) {
    const slug = descriptor.id;
    const range = [fromDate, toDate].filter(Boolean).join('_').replace(/-/g, '');
    return `${slug}${range ? '-' + range : ''}.pdf`;
}

async function createPdf(descriptor, data, company, fromDate, toDate) {
    const pdfMake = await getPdfMake();
    const docDef = buildReportDoc(descriptor, data, company, fromDate, toDate);
    return { instance: pdfMake.createPdf(docDef), name: fileName(descriptor, fromDate, toDate) };
}

export async function openReportPdf(descriptor, data, company, fromDate, toDate) {
    const { instance } = await createPdf(descriptor, data, company, fromDate, toDate);
    instance.open();
}

export async function saveReportPdf(descriptor, data, company, fromDate, toDate) {
    const { instance, name } = await createPdf(descriptor, data, company, fromDate, toDate);
    instance.download(name);
}

export async function printReportPdf(descriptor, data, company, fromDate, toDate) {
    const { instance } = await createPdf(descriptor, data, company, fromDate, toDate);
    instance.print();
}
